platform :ios, '13.0'

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods flutter_application_path
end

target 'RunnerTests' do
  inherit! :search_paths
end
